######################################################################
#
# File name : ControlUnit_tb.udo
# Created on: Tue Jul 13 19:15:27 +0800 2021
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
